version: '3'

services:
    products_core_database: 
        image: mysql
        container_name: products_core_database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: products_core_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - products_database_data:/var/lib/mysql
    products_core_backend:
        build: ProductCoreApplication
        container_name: products_core_backend
        ports:
          - "8080:8080"
        volumes:
          - ./ProductCoreApplication:/ProductCoreApplication
        depends_on:
          - products_core_database
        links:
          - products_core_database

volumes:
    products_database_data:
