version: '3'

services:
  eurekaserver:
    build: eurekaServer
    container_name: eurekaserver
    ports:
      - 8761:8761
    volumes:
      - ./eurekaServer:/EurekaServerApplication
  products_core_database:
    image: mysql
    container_name: products_core_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products_core_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - products_database_data:/var/lib/mysql
  products_core_backend:
    build: ProductCoreApplication
    container_name: products_core_backend
    ports:
      - 8080:8080
    volumes:
      - ./ProductCoreApplication:/ProductCoreApplication
    depends_on:
      - products_core_database
      - eurekaserver
  user_core_database:
    image: mysql
    container_name: user_core_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_core_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - user_core_database_data:/var/lib/mysql
  user_core_backend:
    build: UserCoreApplication
    container_name: user_core_backend
    volumes:
      - ./UserCoreApplication:/UserCoreApplication
    ports:
      - 8081:8081
    depends_on:
      - user_core_database
      - eurekaserver
  category_core_database:
    image: mysql
    container_name: category_core_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: category_core_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PORT: 3308
    ports:
      - 3308:3308
    volumes:
      - category_core_database_data:/var/lib/mysql
  category_core_backend:
    build: CategoryCoreApplication
    container_name: category_core_backend
    ports:
      - 8082:8082
    depends_on:
      - category_core_database
      - eurekaserver
  user_composite_backend:
    build: UserCmpApplication
    container_name: user_composite_backend
    ports:
      - 8083:8083
    depends_on:
      - user_core_database
      - user_core_backend
      - eurekaserver
  catalog_composite_backend:
    build: CatalogCmpApplication
    container_name: catalog_composite_backend
    ports:
      - 8084:8084
    depends_on:
      - products_core_database
      - products_core_backend
      - category_core_database
      - category_core_backend
      - eurekaserver
volumes:
  products_database_data:
  user_core_database_data:
  category_core_database_data:
