version: '3'

services:
  eurekaserver:
    build: eurekaServer
    container_name: eurekaserver
    ports:
      - 8761:8761
    volumes:
      - ./eurekaServer:/EurekaServerApplication
  category_core_database:
      image: mysql
      container_name: category_core_database
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: category_core_database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          PORT: 3308
      ports:
        - 3308:3306
      volumes:
        - category_core_database_data:/var/lib/mysql
  category_core_backend:
      build: CategoryCoreApplication
      container_name: category_core_backend
      ports:
        - 8082:8080
      depends_on:
        - category_core_database
        - eurekaserver
      links:
        - category_core_database
        - eurekaserver
volumes:
    category_core_database_data:

