version: '3'

services:
    eurekaserver:
        build: eurekaServer
        container_name: eurekaserver
        ports:
            - 8761:8761
        #volumes:
        #    - ./eurekaServer:/EurekaServerApplication
    products_core_database: 
        image: mysql
        container_name: products_core_database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: products_core_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - products_database_data:/var/lib/mysql
    products_core_backend:
        build: ProductCoreApplication
        container_name: products_core_backend
        ports:
          - 8080:8080
        volumes:
          - ./ProductCoreApplication:/ProductCoreApplication
        depends_on:
          - products_core_database
          - eurekaserver
        links:
          - products_core_database
          - eurekaserver

volumes:
    products_database_data:

