server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsSyncEmpty: 0

security:
  oauth2:
    resource:
      id: eureka-client
      jwt:
        key-uri: http://auth/auth/oauth2/keys