server:
  port: 8090
  servlet:
    context-path: /client

spring:
  application:
    name: client
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      webshop-client-password:
        client-id: webshop-client
        client-secret: secretPassword
        grant-type: password
        access-token-uri: http://localhost:8086/auth/oauth/token
        scope: read, write
webshop:
  base-uri: http://localhost:8085