server:
  port: 8090
  servlet:
    context-path: /client

spring:
  application:
    name: client
  thymeleaf:
    cache: false
  cloud:
    config:
      enable: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

security:
  oauth2:
    client:
      webshop-client-password:
        client-id: webshop-client
        client-secret: secretPassword
        grant-type: password
        access-token-uri: http://auth:8086/auth/oauth/token
        scope: read, write
webshop:
  base-uri: http://zuulserver