server:
  port: 8086
spring:
  application:
    name: auth
  cloud:
    config:
      enable: false
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /info
#    healthCheckUrlPath: /health
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://eurekaserver:8761/eureka/