server:
  port: 8085
spring:
  application:
    name: zuulserver
  cloud:
    config:
      enable: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  ignoredServices: '*'
  routes:
    userCompositeService:
      path: /user/**
      stripPrefix: false
    duckduck:
      path: /duckduckgo/**
      url: https://duckduckgo.com
      stripPrefix: false
    catalogCategory:
      path: /category/**
      serviceId: catalogCompositeService
      stripPrefix: false
    catalogProduct:
      path: /product/**
      serviceId: catalogCompositeService
      stripPrefix: false
    auth:
      sensitiveHeaders:
        serviceId: eureka-client
      path: /auth/**
      stripPrefix: false
security:
  oauth2:
    client:
      client-id: webshop-client
      client-secret: secretPassword
    resource:
      token-info-uri: http://auth:8086/auth/oauth/authorize
      prefer-token-info: true