server:
  port: 8085
spring:
  application:
    name: zuulserver
  cloud:
    config:
      enable: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  ignoredServices: '*'
  routes:
    userCompositeService:
      path: /user/**
      stripPrefix: false
    catalogCategory:
      path: /category/**
      serviceId: catalogCompositeService
      stripPrefix: false
    catalogProduct:
      path: /product/**
      serviceId: catalogCompositeService
      stripPrefix: false
    auth:
      sensitive-headers:
        - Authorization,Cookie,Set-Cookie
      path: /auth/**
      stripPrefix: false
security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://auth:8086/auth/oauth2/keys
