server:
  port: 8085
spring:
  application:
    name: zuulserver
  cloud:
    config:
      enable: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  ignoredServices: '*'
  routes:
    userCompositeService:
      path: /user/**
      stripPrefix: false
    catalogCategory:
      path: /category/**
      serviceId: catalogCompositeService
      stripPrefix: false
    catalogProduct:
      path: /product/**
      serviceId: catalogCompositeService
      stripPrefix: false
    auth:
      sensitiveHeaders:
        serviceId: eureka-client
      path: /auth/**
      stripPrefix: false
security:
  oauth2:
    client:
      access-token-uri: http://auth/auth/oauth/token
      user-authorization-uri: http://auth/auth/oauth/authorize
      client-id: webshop-client
      client-secret: secretPassword
    resource:
      user-info-uri: http://auth/auth/current
      prefer-token-info: false
      jwt:
        key-uri: http://auth/auth/oauth2/keys
