server:
  port: 8086
  servlet:
    context-path: /auth
spring:
  application:
    name: auth

  cloud:
    config:
      enable: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"