server:
  port: 8083
spring:
  application:
    name: userCompositeService
  security:
    oauth2:
      resource:
        token-info-uri: http://auth/auth/oauth/check_token
      client:
        client-id: webshop-client
        client-secret: secretPassword
        grant-type: client_credentials
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"