server:
  port: 8083
spring:
  application:
    name: userCompositeService
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth/auth/oauth2/keys
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"